apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: guestbook2-monitor
  name: guestbook2-monitor
  namespace: guestbook2 
spec:
  endpoints:
    - interval: 30s
  port: http
  scheme: http
  selector:
  matchLabels:
      project: guestbook2
